/*
 * Car info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"net/http"
)

func InfoGet(w http.ResponseWriter, r *http.Request) {

	regNum := r.URL.Query().Get("regNum")
	if regNum == "" {
		http.Error(w, "Bad request", http.StatusBadRequest)
	}

	car := RandomCar(regNum)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	d, err := json.Marshal(car)

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}

	w.Write(d)
}
