/*
 * Car info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"net/http"
	"regexp"
)

func InfoGet(w http.ResponseWriter, r *http.Request) {

	regNum := r.URL.Query().Get("regNum")
	if !checkRegNum(regNum) {

		http.Error(w, "Поле regNum содержит некорректные данные", http.StatusBadRequest)
		return
	}

	car := RandomCar(regNum)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	d, err := json.Marshal(car)

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}

	w.Write(d)
}

func checkRegNum(regNum string) bool {
	pattern := `^[a-zA-Zа-яА-Я]\d{3}[a-zA-Zа-яА-Я][a-zA-Zа-яА-Я]\d{3}$`
	match, _ := regexp.MatchString(pattern, regNum)
	return match
}
